//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Observer
{
	public Observer()
	{
	}

	public virtual void update()
	{
		Console.WriteLine("Flag value changed in Subject");
	}

}

