//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ObserverPatternEx
{
	public ObserverPatternEx()
	{
	}

	public static void Main(String[] args)
	{
		Console.WriteLine("***Observer Pattern Demo***\n");
        Observer o = new Observer();
        Subject sub = new Subject();
        sub.Register(o);
        Console.WriteLine("Setting Flag = 5");
        sub.SetFlag(5);
        Console.WriteLine("Setting Flag = 25");
        sub.SetFlag(25);
        sub.Unregister(o);
        
        // No notification this time to o Since it is unregistered.
        Console.WriteLine("Setting Flag = 50");
        sub.SetFlag(50);
	}

}

