//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Subject : ISubject
{
	private int flag_
	{
		get;
		set;
	}

    private List<Observer> observer_list_ = new List<Observer>();

	public Subject()
	{
	}

	public virtual int GetFlag()
	{
		return flag_;
	}

	public virtual void SetFlag(int flag)
	{
		flag_ = flag;
        NotifyObservers();
	}

	public virtual void Register(Observer o)
	{
		observer_list_.Add(o);
	}

	public virtual void Unregister(Observer o)
	{
		observer_list_.Remove(o);
	}

	public virtual void NotifyObservers()
	{
        foreach (Observer o in observer_list_)
        {
            o.update();
        }
	}

}

