// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tms.proto

#ifndef PROTOBUF_tms_2eproto__INCLUDED
#define PROTOBUF_tms_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace tms {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_tms_2eproto();
void protobuf_AssignDesc_tms_2eproto();
void protobuf_ShutdownFile_tms_2eproto();

class StateServerReq;
class ServerInfo;
class ServerOut;
class ServerInfoList;
class TargtServerID;
class TargtServerIDList;
class TargetOnlineInfo;
class UserLoginFlag;
class UserLoginFlagList;
class UserOnlineNotify;
class TalkMsgBaseList;
class TalkMsgBaseList_TalkMsgBase;
class ChatMsgBaseList;
class ChatMsgBaseList_ChatMsgBase;
class UserMsgIDList;
class UserMsgIDList_UserMsgID;

enum StateServerReq_cmd {
  StateServerReq_cmd_ChatMsgIDALL = 1,
  StateServerReq_cmd_TalkMsgIDALL = 2,
  StateServerReq_cmd_UserMsgIDALL = 3,
  StateServerReq_cmd_TargetInfoALL = 4,
  StateServerReq_cmd_TargtServerIDALL = 5,
  StateServerReq_cmd_UserLoginFlagALL = 6
};
bool StateServerReq_cmd_IsValid(int value);
const StateServerReq_cmd StateServerReq_cmd_cmd_MIN = StateServerReq_cmd_ChatMsgIDALL;
const StateServerReq_cmd StateServerReq_cmd_cmd_MAX = StateServerReq_cmd_UserLoginFlagALL;
const int StateServerReq_cmd_cmd_ARRAYSIZE = StateServerReq_cmd_cmd_MAX + 1;

const ::google::protobuf::EnumDescriptor* StateServerReq_cmd_descriptor();
inline const ::std::string& StateServerReq_cmd_Name(StateServerReq_cmd value) {
  return ::google::protobuf::internal::NameOfEnum(
    StateServerReq_cmd_descriptor(), value);
}
inline bool StateServerReq_cmd_Parse(
    const ::std::string& name, StateServerReq_cmd* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StateServerReq_cmd>(
    StateServerReq_cmd_descriptor(), name, value);
}
// ===================================================================

class StateServerReq : public ::google::protobuf::Message {
 public:
  StateServerReq();
  virtual ~StateServerReq();

  StateServerReq(const StateServerReq& from);

  inline StateServerReq& operator=(const StateServerReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StateServerReq& default_instance();

  void Swap(StateServerReq* other);

  // implements Message ----------------------------------------------

  StateServerReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StateServerReq& from);
  void MergeFrom(const StateServerReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef StateServerReq_cmd cmd;
  static const cmd ChatMsgIDALL = StateServerReq_cmd_ChatMsgIDALL;
  static const cmd TalkMsgIDALL = StateServerReq_cmd_TalkMsgIDALL;
  static const cmd UserMsgIDALL = StateServerReq_cmd_UserMsgIDALL;
  static const cmd TargetInfoALL = StateServerReq_cmd_TargetInfoALL;
  static const cmd TargtServerIDALL = StateServerReq_cmd_TargtServerIDALL;
  static const cmd UserLoginFlagALL = StateServerReq_cmd_UserLoginFlagALL;
  static inline bool cmd_IsValid(int value) {
    return StateServerReq_cmd_IsValid(value);
  }
  static const cmd cmd_MIN =
    StateServerReq_cmd_cmd_MIN;
  static const cmd cmd_MAX =
    StateServerReq_cmd_cmd_MAX;
  static const int cmd_ARRAYSIZE =
    StateServerReq_cmd_cmd_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  cmd_descriptor() {
    return StateServerReq_cmd_descriptor();
  }
  static inline const ::std::string& cmd_Name(cmd value) {
    return StateServerReq_cmd_Name(value);
  }
  static inline bool cmd_Parse(const ::std::string& name,
      cmd* value) {
    return StateServerReq_cmd_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .tms.StateServerReq.cmd ncmd = 1;
  inline bool has_ncmd() const;
  inline void clear_ncmd();
  static const int kNcmdFieldNumber = 1;
  inline ::tms::StateServerReq_cmd ncmd() const;
  inline void set_ncmd(::tms::StateServerReq_cmd value);

  // @@protoc_insertion_point(class_scope:tms.StateServerReq)
 private:
  inline void set_has_ncmd();
  inline void clear_has_ncmd();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int ncmd_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static StateServerReq* default_instance_;
};
// -------------------------------------------------------------------

class ServerInfo : public ::google::protobuf::Message {
 public:
  ServerInfo();
  virtual ~ServerInfo();

  ServerInfo(const ServerInfo& from);

  inline ServerInfo& operator=(const ServerInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerInfo& default_instance();

  void Swap(ServerInfo* other);

  // implements Message ----------------------------------------------

  ServerInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerInfo& from);
  void MergeFrom(const ServerInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uServerID = 1;
  inline bool has_userverid() const;
  inline void clear_userverid();
  static const int kUServerIDFieldNumber = 1;
  inline ::google::protobuf::uint32 userverid() const;
  inline void set_userverid(::google::protobuf::uint32 value);

  // required string strServerIP = 2;
  inline bool has_strserverip() const;
  inline void clear_strserverip();
  static const int kStrServerIPFieldNumber = 2;
  inline const ::std::string& strserverip() const;
  inline void set_strserverip(const ::std::string& value);
  inline void set_strserverip(const char* value);
  inline void set_strserverip(const char* value, size_t size);
  inline ::std::string* mutable_strserverip();
  inline ::std::string* release_strserverip();
  inline void set_allocated_strserverip(::std::string* strserverip);

  // required uint32 usServerPort = 3;
  inline bool has_usserverport() const;
  inline void clear_usserverport();
  static const int kUsServerPortFieldNumber = 3;
  inline ::google::protobuf::uint32 usserverport() const;
  inline void set_usserverport(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tms.ServerInfo)
 private:
  inline void set_has_userverid();
  inline void clear_has_userverid();
  inline void set_has_strserverip();
  inline void clear_has_strserverip();
  inline void set_has_usserverport();
  inline void clear_has_usserverport();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* strserverip_;
  ::google::protobuf::uint32 userverid_;
  ::google::protobuf::uint32 usserverport_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static ServerInfo* default_instance_;
};
// -------------------------------------------------------------------

class ServerOut : public ::google::protobuf::Message {
 public:
  ServerOut();
  virtual ~ServerOut();

  ServerOut(const ServerOut& from);

  inline ServerOut& operator=(const ServerOut& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerOut& default_instance();

  void Swap(ServerOut* other);

  // implements Message ----------------------------------------------

  ServerOut* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerOut& from);
  void MergeFrom(const ServerOut& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uServerID = 1;
  inline bool has_userverid() const;
  inline void clear_userverid();
  static const int kUServerIDFieldNumber = 1;
  inline ::google::protobuf::uint32 userverid() const;
  inline void set_userverid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tms.ServerOut)
 private:
  inline void set_has_userverid();
  inline void clear_has_userverid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 userverid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static ServerOut* default_instance_;
};
// -------------------------------------------------------------------

class ServerInfoList : public ::google::protobuf::Message {
 public:
  ServerInfoList();
  virtual ~ServerInfoList();

  ServerInfoList(const ServerInfoList& from);

  inline ServerInfoList& operator=(const ServerInfoList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerInfoList& default_instance();

  void Swap(ServerInfoList* other);

  // implements Message ----------------------------------------------

  ServerInfoList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerInfoList& from);
  void MergeFrom(const ServerInfoList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tms.ServerInfo ServerInfos = 1;
  inline int serverinfos_size() const;
  inline void clear_serverinfos();
  static const int kServerInfosFieldNumber = 1;
  inline const ::tms::ServerInfo& serverinfos(int index) const;
  inline ::tms::ServerInfo* mutable_serverinfos(int index);
  inline ::tms::ServerInfo* add_serverinfos();
  inline const ::google::protobuf::RepeatedPtrField< ::tms::ServerInfo >&
      serverinfos() const;
  inline ::google::protobuf::RepeatedPtrField< ::tms::ServerInfo >*
      mutable_serverinfos();

  // @@protoc_insertion_point(class_scope:tms.ServerInfoList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::tms::ServerInfo > serverinfos_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static ServerInfoList* default_instance_;
};
// -------------------------------------------------------------------

class TargtServerID : public ::google::protobuf::Message {
 public:
  TargtServerID();
  virtual ~TargtServerID();

  TargtServerID(const TargtServerID& from);

  inline TargtServerID& operator=(const TargtServerID& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TargtServerID& default_instance();

  void Swap(TargtServerID* other);

  // implements Message ----------------------------------------------

  TargtServerID* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TargtServerID& from);
  void MergeFrom(const TargtServerID& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uTargetID = 1 [default = 0];
  inline bool has_utargetid() const;
  inline void clear_utargetid();
  static const int kUTargetIDFieldNumber = 1;
  inline ::google::protobuf::uint32 utargetid() const;
  inline void set_utargetid(::google::protobuf::uint32 value);

  // required uint32 uServerID = 2 [default = 0];
  inline bool has_userverid() const;
  inline void clear_userverid();
  static const int kUServerIDFieldNumber = 2;
  inline ::google::protobuf::uint32 userverid() const;
  inline void set_userverid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tms.TargtServerID)
 private:
  inline void set_has_utargetid();
  inline void clear_has_utargetid();
  inline void set_has_userverid();
  inline void clear_has_userverid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 utargetid_;
  ::google::protobuf::uint32 userverid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static TargtServerID* default_instance_;
};
// -------------------------------------------------------------------

class TargtServerIDList : public ::google::protobuf::Message {
 public:
  TargtServerIDList();
  virtual ~TargtServerIDList();

  TargtServerIDList(const TargtServerIDList& from);

  inline TargtServerIDList& operator=(const TargtServerIDList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TargtServerIDList& default_instance();

  void Swap(TargtServerIDList* other);

  // implements Message ----------------------------------------------

  TargtServerIDList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TargtServerIDList& from);
  void MergeFrom(const TargtServerIDList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tms.TargtServerID TargtServerIDs = 1;
  inline int targtserverids_size() const;
  inline void clear_targtserverids();
  static const int kTargtServerIDsFieldNumber = 1;
  inline const ::tms::TargtServerID& targtserverids(int index) const;
  inline ::tms::TargtServerID* mutable_targtserverids(int index);
  inline ::tms::TargtServerID* add_targtserverids();
  inline const ::google::protobuf::RepeatedPtrField< ::tms::TargtServerID >&
      targtserverids() const;
  inline ::google::protobuf::RepeatedPtrField< ::tms::TargtServerID >*
      mutable_targtserverids();

  // @@protoc_insertion_point(class_scope:tms.TargtServerIDList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::tms::TargtServerID > targtserverids_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static TargtServerIDList* default_instance_;
};
// -------------------------------------------------------------------

class TargetOnlineInfo : public ::google::protobuf::Message {
 public:
  TargetOnlineInfo();
  virtual ~TargetOnlineInfo();

  TargetOnlineInfo(const TargetOnlineInfo& from);

  inline TargetOnlineInfo& operator=(const TargetOnlineInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TargetOnlineInfo& default_instance();

  void Swap(TargetOnlineInfo* other);

  // implements Message ----------------------------------------------

  TargetOnlineInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TargetOnlineInfo& from);
  void MergeFrom(const TargetOnlineInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uAccountID = 1 [default = 0];
  inline bool has_uaccountid() const;
  inline void clear_uaccountid();
  static const int kUAccountIDFieldNumber = 1;
  inline ::google::protobuf::uint32 uaccountid() const;
  inline void set_uaccountid(::google::protobuf::uint32 value);

  // required uint32 uSessionID = 2 [default = 0];
  inline bool has_usessionid() const;
  inline void clear_usessionid();
  static const int kUSessionIDFieldNumber = 2;
  inline ::google::protobuf::uint32 usessionid() const;
  inline void set_usessionid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tms.TargetOnlineInfo)
 private:
  inline void set_has_uaccountid();
  inline void clear_has_uaccountid();
  inline void set_has_usessionid();
  inline void clear_has_usessionid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 uaccountid_;
  ::google::protobuf::uint32 usessionid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static TargetOnlineInfo* default_instance_;
};
// -------------------------------------------------------------------

class UserLoginFlag : public ::google::protobuf::Message {
 public:
  UserLoginFlag();
  virtual ~UserLoginFlag();

  UserLoginFlag(const UserLoginFlag& from);

  inline UserLoginFlag& operator=(const UserLoginFlag& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserLoginFlag& default_instance();

  void Swap(UserLoginFlag* other);

  // implements Message ----------------------------------------------

  UserLoginFlag* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserLoginFlag& from);
  void MergeFrom(const UserLoginFlag& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uAccountID = 1 [default = 0];
  inline bool has_uaccountid() const;
  inline void clear_uaccountid();
  static const int kUAccountIDFieldNumber = 1;
  inline ::google::protobuf::uint32 uaccountid() const;
  inline void set_uaccountid(::google::protobuf::uint32 value);

  // required uint32 uLoginFlags = 2 [default = 0];
  inline bool has_uloginflags() const;
  inline void clear_uloginflags();
  static const int kULoginFlagsFieldNumber = 2;
  inline ::google::protobuf::uint32 uloginflags() const;
  inline void set_uloginflags(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tms.UserLoginFlag)
 private:
  inline void set_has_uaccountid();
  inline void clear_has_uaccountid();
  inline void set_has_uloginflags();
  inline void clear_has_uloginflags();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 uaccountid_;
  ::google::protobuf::uint32 uloginflags_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static UserLoginFlag* default_instance_;
};
// -------------------------------------------------------------------

class UserLoginFlagList : public ::google::protobuf::Message {
 public:
  UserLoginFlagList();
  virtual ~UserLoginFlagList();

  UserLoginFlagList(const UserLoginFlagList& from);

  inline UserLoginFlagList& operator=(const UserLoginFlagList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserLoginFlagList& default_instance();

  void Swap(UserLoginFlagList* other);

  // implements Message ----------------------------------------------

  UserLoginFlagList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserLoginFlagList& from);
  void MergeFrom(const UserLoginFlagList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tms.UserLoginFlag UserLoginFlags = 1;
  inline int userloginflags_size() const;
  inline void clear_userloginflags();
  static const int kUserLoginFlagsFieldNumber = 1;
  inline const ::tms::UserLoginFlag& userloginflags(int index) const;
  inline ::tms::UserLoginFlag* mutable_userloginflags(int index);
  inline ::tms::UserLoginFlag* add_userloginflags();
  inline const ::google::protobuf::RepeatedPtrField< ::tms::UserLoginFlag >&
      userloginflags() const;
  inline ::google::protobuf::RepeatedPtrField< ::tms::UserLoginFlag >*
      mutable_userloginflags();

  // @@protoc_insertion_point(class_scope:tms.UserLoginFlagList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::tms::UserLoginFlag > userloginflags_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static UserLoginFlagList* default_instance_;
};
// -------------------------------------------------------------------

class UserOnlineNotify : public ::google::protobuf::Message {
 public:
  UserOnlineNotify();
  virtual ~UserOnlineNotify();

  UserOnlineNotify(const UserOnlineNotify& from);

  inline UserOnlineNotify& operator=(const UserOnlineNotify& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserOnlineNotify& default_instance();

  void Swap(UserOnlineNotify* other);

  // implements Message ----------------------------------------------

  UserOnlineNotify* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserOnlineNotify& from);
  void MergeFrom(const UserOnlineNotify& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uAccountID = 1 [default = 0];
  inline bool has_uaccountid() const;
  inline void clear_uaccountid();
  static const int kUAccountIDFieldNumber = 1;
  inline ::google::protobuf::uint32 uaccountid() const;
  inline void set_uaccountid(::google::protobuf::uint32 value);

  // required uint32 uServerID = 2 [default = 0];
  inline bool has_userverid() const;
  inline void clear_userverid();
  static const int kUServerIDFieldNumber = 2;
  inline ::google::protobuf::uint32 userverid() const;
  inline void set_userverid(::google::protobuf::uint32 value);

  // required uint32 uLoginFlag = 3 [default = 0];
  inline bool has_uloginflag() const;
  inline void clear_uloginflag();
  static const int kULoginFlagFieldNumber = 3;
  inline ::google::protobuf::uint32 uloginflag() const;
  inline void set_uloginflag(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tms.UserOnlineNotify)
 private:
  inline void set_has_uaccountid();
  inline void clear_has_uaccountid();
  inline void set_has_userverid();
  inline void clear_has_userverid();
  inline void set_has_uloginflag();
  inline void clear_has_uloginflag();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 uaccountid_;
  ::google::protobuf::uint32 userverid_;
  ::google::protobuf::uint32 uloginflag_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static UserOnlineNotify* default_instance_;
};
// -------------------------------------------------------------------

class TalkMsgBaseList_TalkMsgBase : public ::google::protobuf::Message {
 public:
  TalkMsgBaseList_TalkMsgBase();
  virtual ~TalkMsgBaseList_TalkMsgBase();

  TalkMsgBaseList_TalkMsgBase(const TalkMsgBaseList_TalkMsgBase& from);

  inline TalkMsgBaseList_TalkMsgBase& operator=(const TalkMsgBaseList_TalkMsgBase& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TalkMsgBaseList_TalkMsgBase& default_instance();

  void Swap(TalkMsgBaseList_TalkMsgBase* other);

  // implements Message ----------------------------------------------

  TalkMsgBaseList_TalkMsgBase* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TalkMsgBaseList_TalkMsgBase& from);
  void MergeFrom(const TalkMsgBaseList_TalkMsgBase& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 uTalkID = 1 [default = 0];
  inline bool has_utalkid() const;
  inline void clear_utalkid();
  static const int kUTalkIDFieldNumber = 1;
  inline ::google::protobuf::uint64 utalkid() const;
  inline void set_utalkid(::google::protobuf::uint64 value);

  // required uint32 uMsgID = 2 [default = 0];
  inline bool has_umsgid() const;
  inline void clear_umsgid();
  static const int kUMsgIDFieldNumber = 2;
  inline ::google::protobuf::uint32 umsgid() const;
  inline void set_umsgid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tms.TalkMsgBaseList.TalkMsgBase)
 private:
  inline void set_has_utalkid();
  inline void clear_has_utalkid();
  inline void set_has_umsgid();
  inline void clear_has_umsgid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 utalkid_;
  ::google::protobuf::uint32 umsgid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static TalkMsgBaseList_TalkMsgBase* default_instance_;
};
// -------------------------------------------------------------------

class TalkMsgBaseList : public ::google::protobuf::Message {
 public:
  TalkMsgBaseList();
  virtual ~TalkMsgBaseList();

  TalkMsgBaseList(const TalkMsgBaseList& from);

  inline TalkMsgBaseList& operator=(const TalkMsgBaseList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TalkMsgBaseList& default_instance();

  void Swap(TalkMsgBaseList* other);

  // implements Message ----------------------------------------------

  TalkMsgBaseList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TalkMsgBaseList& from);
  void MergeFrom(const TalkMsgBaseList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef TalkMsgBaseList_TalkMsgBase TalkMsgBase;

  // accessors -------------------------------------------------------

  // repeated .tms.TalkMsgBaseList.TalkMsgBase TalkMsgBases = 1;
  inline int talkmsgbases_size() const;
  inline void clear_talkmsgbases();
  static const int kTalkMsgBasesFieldNumber = 1;
  inline const ::tms::TalkMsgBaseList_TalkMsgBase& talkmsgbases(int index) const;
  inline ::tms::TalkMsgBaseList_TalkMsgBase* mutable_talkmsgbases(int index);
  inline ::tms::TalkMsgBaseList_TalkMsgBase* add_talkmsgbases();
  inline const ::google::protobuf::RepeatedPtrField< ::tms::TalkMsgBaseList_TalkMsgBase >&
      talkmsgbases() const;
  inline ::google::protobuf::RepeatedPtrField< ::tms::TalkMsgBaseList_TalkMsgBase >*
      mutable_talkmsgbases();

  // @@protoc_insertion_point(class_scope:tms.TalkMsgBaseList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::tms::TalkMsgBaseList_TalkMsgBase > talkmsgbases_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static TalkMsgBaseList* default_instance_;
};
// -------------------------------------------------------------------

class ChatMsgBaseList_ChatMsgBase : public ::google::protobuf::Message {
 public:
  ChatMsgBaseList_ChatMsgBase();
  virtual ~ChatMsgBaseList_ChatMsgBase();

  ChatMsgBaseList_ChatMsgBase(const ChatMsgBaseList_ChatMsgBase& from);

  inline ChatMsgBaseList_ChatMsgBase& operator=(const ChatMsgBaseList_ChatMsgBase& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatMsgBaseList_ChatMsgBase& default_instance();

  void Swap(ChatMsgBaseList_ChatMsgBase* other);

  // implements Message ----------------------------------------------

  ChatMsgBaseList_ChatMsgBase* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatMsgBaseList_ChatMsgBase& from);
  void MergeFrom(const ChatMsgBaseList_ChatMsgBase& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uChatID = 1 [default = 0];
  inline bool has_uchatid() const;
  inline void clear_uchatid();
  static const int kUChatIDFieldNumber = 1;
  inline ::google::protobuf::uint32 uchatid() const;
  inline void set_uchatid(::google::protobuf::uint32 value);

  // required uint32 uMsgID = 2 [default = 0];
  inline bool has_umsgid() const;
  inline void clear_umsgid();
  static const int kUMsgIDFieldNumber = 2;
  inline ::google::protobuf::uint32 umsgid() const;
  inline void set_umsgid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tms.ChatMsgBaseList.ChatMsgBase)
 private:
  inline void set_has_uchatid();
  inline void clear_has_uchatid();
  inline void set_has_umsgid();
  inline void clear_has_umsgid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 uchatid_;
  ::google::protobuf::uint32 umsgid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static ChatMsgBaseList_ChatMsgBase* default_instance_;
};
// -------------------------------------------------------------------

class ChatMsgBaseList : public ::google::protobuf::Message {
 public:
  ChatMsgBaseList();
  virtual ~ChatMsgBaseList();

  ChatMsgBaseList(const ChatMsgBaseList& from);

  inline ChatMsgBaseList& operator=(const ChatMsgBaseList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatMsgBaseList& default_instance();

  void Swap(ChatMsgBaseList* other);

  // implements Message ----------------------------------------------

  ChatMsgBaseList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatMsgBaseList& from);
  void MergeFrom(const ChatMsgBaseList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ChatMsgBaseList_ChatMsgBase ChatMsgBase;

  // accessors -------------------------------------------------------

  // repeated .tms.ChatMsgBaseList.ChatMsgBase ChatMsgBases = 1;
  inline int chatmsgbases_size() const;
  inline void clear_chatmsgbases();
  static const int kChatMsgBasesFieldNumber = 1;
  inline const ::tms::ChatMsgBaseList_ChatMsgBase& chatmsgbases(int index) const;
  inline ::tms::ChatMsgBaseList_ChatMsgBase* mutable_chatmsgbases(int index);
  inline ::tms::ChatMsgBaseList_ChatMsgBase* add_chatmsgbases();
  inline const ::google::protobuf::RepeatedPtrField< ::tms::ChatMsgBaseList_ChatMsgBase >&
      chatmsgbases() const;
  inline ::google::protobuf::RepeatedPtrField< ::tms::ChatMsgBaseList_ChatMsgBase >*
      mutable_chatmsgbases();

  // @@protoc_insertion_point(class_scope:tms.ChatMsgBaseList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::tms::ChatMsgBaseList_ChatMsgBase > chatmsgbases_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static ChatMsgBaseList* default_instance_;
};
// -------------------------------------------------------------------

class UserMsgIDList_UserMsgID : public ::google::protobuf::Message {
 public:
  UserMsgIDList_UserMsgID();
  virtual ~UserMsgIDList_UserMsgID();

  UserMsgIDList_UserMsgID(const UserMsgIDList_UserMsgID& from);

  inline UserMsgIDList_UserMsgID& operator=(const UserMsgIDList_UserMsgID& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserMsgIDList_UserMsgID& default_instance();

  void Swap(UserMsgIDList_UserMsgID* other);

  // implements Message ----------------------------------------------

  UserMsgIDList_UserMsgID* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserMsgIDList_UserMsgID& from);
  void MergeFrom(const UserMsgIDList_UserMsgID& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uSendID = 1 [default = 0];
  inline bool has_usendid() const;
  inline void clear_usendid();
  static const int kUSendIDFieldNumber = 1;
  inline ::google::protobuf::uint32 usendid() const;
  inline void set_usendid(::google::protobuf::uint32 value);

  // required uint32 uTargetID = 2 [default = 0];
  inline bool has_utargetid() const;
  inline void clear_utargetid();
  static const int kUTargetIDFieldNumber = 2;
  inline ::google::protobuf::uint32 utargetid() const;
  inline void set_utargetid(::google::protobuf::uint32 value);

  // required uint32 uMsgID = 3 [default = 0];
  inline bool has_umsgid() const;
  inline void clear_umsgid();
  static const int kUMsgIDFieldNumber = 3;
  inline ::google::protobuf::uint32 umsgid() const;
  inline void set_umsgid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tms.UserMsgIDList.UserMsgID)
 private:
  inline void set_has_usendid();
  inline void clear_has_usendid();
  inline void set_has_utargetid();
  inline void clear_has_utargetid();
  inline void set_has_umsgid();
  inline void clear_has_umsgid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 usendid_;
  ::google::protobuf::uint32 utargetid_;
  ::google::protobuf::uint32 umsgid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static UserMsgIDList_UserMsgID* default_instance_;
};
// -------------------------------------------------------------------

class UserMsgIDList : public ::google::protobuf::Message {
 public:
  UserMsgIDList();
  virtual ~UserMsgIDList();

  UserMsgIDList(const UserMsgIDList& from);

  inline UserMsgIDList& operator=(const UserMsgIDList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserMsgIDList& default_instance();

  void Swap(UserMsgIDList* other);

  // implements Message ----------------------------------------------

  UserMsgIDList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserMsgIDList& from);
  void MergeFrom(const UserMsgIDList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef UserMsgIDList_UserMsgID UserMsgID;

  // accessors -------------------------------------------------------

  // repeated .tms.UserMsgIDList.UserMsgID UserMsgIDs = 1;
  inline int usermsgids_size() const;
  inline void clear_usermsgids();
  static const int kUserMsgIDsFieldNumber = 1;
  inline const ::tms::UserMsgIDList_UserMsgID& usermsgids(int index) const;
  inline ::tms::UserMsgIDList_UserMsgID* mutable_usermsgids(int index);
  inline ::tms::UserMsgIDList_UserMsgID* add_usermsgids();
  inline const ::google::protobuf::RepeatedPtrField< ::tms::UserMsgIDList_UserMsgID >&
      usermsgids() const;
  inline ::google::protobuf::RepeatedPtrField< ::tms::UserMsgIDList_UserMsgID >*
      mutable_usermsgids();

  // @@protoc_insertion_point(class_scope:tms.UserMsgIDList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::tms::UserMsgIDList_UserMsgID > usermsgids_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_tms_2eproto();
  friend void protobuf_AssignDesc_tms_2eproto();
  friend void protobuf_ShutdownFile_tms_2eproto();

  void InitAsDefaultInstance();
  static UserMsgIDList* default_instance_;
};
// ===================================================================


// ===================================================================

// StateServerReq

// required .tms.StateServerReq.cmd ncmd = 1;
inline bool StateServerReq::has_ncmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StateServerReq::set_has_ncmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StateServerReq::clear_has_ncmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StateServerReq::clear_ncmd() {
  ncmd_ = 1;
  clear_has_ncmd();
}
inline ::tms::StateServerReq_cmd StateServerReq::ncmd() const {
  return static_cast< ::tms::StateServerReq_cmd >(ncmd_);
}
inline void StateServerReq::set_ncmd(::tms::StateServerReq_cmd value) {
  assert(::tms::StateServerReq_cmd_IsValid(value));
  set_has_ncmd();
  ncmd_ = value;
}

// -------------------------------------------------------------------

// ServerInfo

// required uint32 uServerID = 1;
inline bool ServerInfo::has_userverid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerInfo::set_has_userverid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerInfo::clear_has_userverid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerInfo::clear_userverid() {
  userverid_ = 0u;
  clear_has_userverid();
}
inline ::google::protobuf::uint32 ServerInfo::userverid() const {
  return userverid_;
}
inline void ServerInfo::set_userverid(::google::protobuf::uint32 value) {
  set_has_userverid();
  userverid_ = value;
}

// required string strServerIP = 2;
inline bool ServerInfo::has_strserverip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ServerInfo::set_has_strserverip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ServerInfo::clear_has_strserverip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ServerInfo::clear_strserverip() {
  if (strserverip_ != &::google::protobuf::internal::kEmptyString) {
    strserverip_->clear();
  }
  clear_has_strserverip();
}
inline const ::std::string& ServerInfo::strserverip() const {
  return *strserverip_;
}
inline void ServerInfo::set_strserverip(const ::std::string& value) {
  set_has_strserverip();
  if (strserverip_ == &::google::protobuf::internal::kEmptyString) {
    strserverip_ = new ::std::string;
  }
  strserverip_->assign(value);
}
inline void ServerInfo::set_strserverip(const char* value) {
  set_has_strserverip();
  if (strserverip_ == &::google::protobuf::internal::kEmptyString) {
    strserverip_ = new ::std::string;
  }
  strserverip_->assign(value);
}
inline void ServerInfo::set_strserverip(const char* value, size_t size) {
  set_has_strserverip();
  if (strserverip_ == &::google::protobuf::internal::kEmptyString) {
    strserverip_ = new ::std::string;
  }
  strserverip_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ServerInfo::mutable_strserverip() {
  set_has_strserverip();
  if (strserverip_ == &::google::protobuf::internal::kEmptyString) {
    strserverip_ = new ::std::string;
  }
  return strserverip_;
}
inline ::std::string* ServerInfo::release_strserverip() {
  clear_has_strserverip();
  if (strserverip_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = strserverip_;
    strserverip_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ServerInfo::set_allocated_strserverip(::std::string* strserverip) {
  if (strserverip_ != &::google::protobuf::internal::kEmptyString) {
    delete strserverip_;
  }
  if (strserverip) {
    set_has_strserverip();
    strserverip_ = strserverip;
  } else {
    clear_has_strserverip();
    strserverip_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required uint32 usServerPort = 3;
inline bool ServerInfo::has_usserverport() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ServerInfo::set_has_usserverport() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ServerInfo::clear_has_usserverport() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ServerInfo::clear_usserverport() {
  usserverport_ = 0u;
  clear_has_usserverport();
}
inline ::google::protobuf::uint32 ServerInfo::usserverport() const {
  return usserverport_;
}
inline void ServerInfo::set_usserverport(::google::protobuf::uint32 value) {
  set_has_usserverport();
  usserverport_ = value;
}

// -------------------------------------------------------------------

// ServerOut

// required uint32 uServerID = 1;
inline bool ServerOut::has_userverid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerOut::set_has_userverid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerOut::clear_has_userverid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerOut::clear_userverid() {
  userverid_ = 0u;
  clear_has_userverid();
}
inline ::google::protobuf::uint32 ServerOut::userverid() const {
  return userverid_;
}
inline void ServerOut::set_userverid(::google::protobuf::uint32 value) {
  set_has_userverid();
  userverid_ = value;
}

// -------------------------------------------------------------------

// ServerInfoList

// repeated .tms.ServerInfo ServerInfos = 1;
inline int ServerInfoList::serverinfos_size() const {
  return serverinfos_.size();
}
inline void ServerInfoList::clear_serverinfos() {
  serverinfos_.Clear();
}
inline const ::tms::ServerInfo& ServerInfoList::serverinfos(int index) const {
  return serverinfos_.Get(index);
}
inline ::tms::ServerInfo* ServerInfoList::mutable_serverinfos(int index) {
  return serverinfos_.Mutable(index);
}
inline ::tms::ServerInfo* ServerInfoList::add_serverinfos() {
  return serverinfos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tms::ServerInfo >&
ServerInfoList::serverinfos() const {
  return serverinfos_;
}
inline ::google::protobuf::RepeatedPtrField< ::tms::ServerInfo >*
ServerInfoList::mutable_serverinfos() {
  return &serverinfos_;
}

// -------------------------------------------------------------------

// TargtServerID

// required uint32 uTargetID = 1 [default = 0];
inline bool TargtServerID::has_utargetid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TargtServerID::set_has_utargetid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TargtServerID::clear_has_utargetid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TargtServerID::clear_utargetid() {
  utargetid_ = 0u;
  clear_has_utargetid();
}
inline ::google::protobuf::uint32 TargtServerID::utargetid() const {
  return utargetid_;
}
inline void TargtServerID::set_utargetid(::google::protobuf::uint32 value) {
  set_has_utargetid();
  utargetid_ = value;
}

// required uint32 uServerID = 2 [default = 0];
inline bool TargtServerID::has_userverid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TargtServerID::set_has_userverid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TargtServerID::clear_has_userverid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TargtServerID::clear_userverid() {
  userverid_ = 0u;
  clear_has_userverid();
}
inline ::google::protobuf::uint32 TargtServerID::userverid() const {
  return userverid_;
}
inline void TargtServerID::set_userverid(::google::protobuf::uint32 value) {
  set_has_userverid();
  userverid_ = value;
}

// -------------------------------------------------------------------

// TargtServerIDList

// repeated .tms.TargtServerID TargtServerIDs = 1;
inline int TargtServerIDList::targtserverids_size() const {
  return targtserverids_.size();
}
inline void TargtServerIDList::clear_targtserverids() {
  targtserverids_.Clear();
}
inline const ::tms::TargtServerID& TargtServerIDList::targtserverids(int index) const {
  return targtserverids_.Get(index);
}
inline ::tms::TargtServerID* TargtServerIDList::mutable_targtserverids(int index) {
  return targtserverids_.Mutable(index);
}
inline ::tms::TargtServerID* TargtServerIDList::add_targtserverids() {
  return targtserverids_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tms::TargtServerID >&
TargtServerIDList::targtserverids() const {
  return targtserverids_;
}
inline ::google::protobuf::RepeatedPtrField< ::tms::TargtServerID >*
TargtServerIDList::mutable_targtserverids() {
  return &targtserverids_;
}

// -------------------------------------------------------------------

// TargetOnlineInfo

// required uint32 uAccountID = 1 [default = 0];
inline bool TargetOnlineInfo::has_uaccountid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TargetOnlineInfo::set_has_uaccountid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TargetOnlineInfo::clear_has_uaccountid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TargetOnlineInfo::clear_uaccountid() {
  uaccountid_ = 0u;
  clear_has_uaccountid();
}
inline ::google::protobuf::uint32 TargetOnlineInfo::uaccountid() const {
  return uaccountid_;
}
inline void TargetOnlineInfo::set_uaccountid(::google::protobuf::uint32 value) {
  set_has_uaccountid();
  uaccountid_ = value;
}

// required uint32 uSessionID = 2 [default = 0];
inline bool TargetOnlineInfo::has_usessionid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TargetOnlineInfo::set_has_usessionid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TargetOnlineInfo::clear_has_usessionid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TargetOnlineInfo::clear_usessionid() {
  usessionid_ = 0u;
  clear_has_usessionid();
}
inline ::google::protobuf::uint32 TargetOnlineInfo::usessionid() const {
  return usessionid_;
}
inline void TargetOnlineInfo::set_usessionid(::google::protobuf::uint32 value) {
  set_has_usessionid();
  usessionid_ = value;
}

// -------------------------------------------------------------------

// UserLoginFlag

// required uint32 uAccountID = 1 [default = 0];
inline bool UserLoginFlag::has_uaccountid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserLoginFlag::set_has_uaccountid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserLoginFlag::clear_has_uaccountid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserLoginFlag::clear_uaccountid() {
  uaccountid_ = 0u;
  clear_has_uaccountid();
}
inline ::google::protobuf::uint32 UserLoginFlag::uaccountid() const {
  return uaccountid_;
}
inline void UserLoginFlag::set_uaccountid(::google::protobuf::uint32 value) {
  set_has_uaccountid();
  uaccountid_ = value;
}

// required uint32 uLoginFlags = 2 [default = 0];
inline bool UserLoginFlag::has_uloginflags() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserLoginFlag::set_has_uloginflags() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserLoginFlag::clear_has_uloginflags() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserLoginFlag::clear_uloginflags() {
  uloginflags_ = 0u;
  clear_has_uloginflags();
}
inline ::google::protobuf::uint32 UserLoginFlag::uloginflags() const {
  return uloginflags_;
}
inline void UserLoginFlag::set_uloginflags(::google::protobuf::uint32 value) {
  set_has_uloginflags();
  uloginflags_ = value;
}

// -------------------------------------------------------------------

// UserLoginFlagList

// repeated .tms.UserLoginFlag UserLoginFlags = 1;
inline int UserLoginFlagList::userloginflags_size() const {
  return userloginflags_.size();
}
inline void UserLoginFlagList::clear_userloginflags() {
  userloginflags_.Clear();
}
inline const ::tms::UserLoginFlag& UserLoginFlagList::userloginflags(int index) const {
  return userloginflags_.Get(index);
}
inline ::tms::UserLoginFlag* UserLoginFlagList::mutable_userloginflags(int index) {
  return userloginflags_.Mutable(index);
}
inline ::tms::UserLoginFlag* UserLoginFlagList::add_userloginflags() {
  return userloginflags_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tms::UserLoginFlag >&
UserLoginFlagList::userloginflags() const {
  return userloginflags_;
}
inline ::google::protobuf::RepeatedPtrField< ::tms::UserLoginFlag >*
UserLoginFlagList::mutable_userloginflags() {
  return &userloginflags_;
}

// -------------------------------------------------------------------

// UserOnlineNotify

// required uint32 uAccountID = 1 [default = 0];
inline bool UserOnlineNotify::has_uaccountid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserOnlineNotify::set_has_uaccountid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserOnlineNotify::clear_has_uaccountid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserOnlineNotify::clear_uaccountid() {
  uaccountid_ = 0u;
  clear_has_uaccountid();
}
inline ::google::protobuf::uint32 UserOnlineNotify::uaccountid() const {
  return uaccountid_;
}
inline void UserOnlineNotify::set_uaccountid(::google::protobuf::uint32 value) {
  set_has_uaccountid();
  uaccountid_ = value;
}

// required uint32 uServerID = 2 [default = 0];
inline bool UserOnlineNotify::has_userverid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserOnlineNotify::set_has_userverid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserOnlineNotify::clear_has_userverid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserOnlineNotify::clear_userverid() {
  userverid_ = 0u;
  clear_has_userverid();
}
inline ::google::protobuf::uint32 UserOnlineNotify::userverid() const {
  return userverid_;
}
inline void UserOnlineNotify::set_userverid(::google::protobuf::uint32 value) {
  set_has_userverid();
  userverid_ = value;
}

// required uint32 uLoginFlag = 3 [default = 0];
inline bool UserOnlineNotify::has_uloginflag() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserOnlineNotify::set_has_uloginflag() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserOnlineNotify::clear_has_uloginflag() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserOnlineNotify::clear_uloginflag() {
  uloginflag_ = 0u;
  clear_has_uloginflag();
}
inline ::google::protobuf::uint32 UserOnlineNotify::uloginflag() const {
  return uloginflag_;
}
inline void UserOnlineNotify::set_uloginflag(::google::protobuf::uint32 value) {
  set_has_uloginflag();
  uloginflag_ = value;
}

// -------------------------------------------------------------------

// TalkMsgBaseList_TalkMsgBase

// required uint64 uTalkID = 1 [default = 0];
inline bool TalkMsgBaseList_TalkMsgBase::has_utalkid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TalkMsgBaseList_TalkMsgBase::set_has_utalkid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TalkMsgBaseList_TalkMsgBase::clear_has_utalkid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TalkMsgBaseList_TalkMsgBase::clear_utalkid() {
  utalkid_ = GOOGLE_ULONGLONG(0);
  clear_has_utalkid();
}
inline ::google::protobuf::uint64 TalkMsgBaseList_TalkMsgBase::utalkid() const {
  return utalkid_;
}
inline void TalkMsgBaseList_TalkMsgBase::set_utalkid(::google::protobuf::uint64 value) {
  set_has_utalkid();
  utalkid_ = value;
}

// required uint32 uMsgID = 2 [default = 0];
inline bool TalkMsgBaseList_TalkMsgBase::has_umsgid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TalkMsgBaseList_TalkMsgBase::set_has_umsgid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TalkMsgBaseList_TalkMsgBase::clear_has_umsgid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TalkMsgBaseList_TalkMsgBase::clear_umsgid() {
  umsgid_ = 0u;
  clear_has_umsgid();
}
inline ::google::protobuf::uint32 TalkMsgBaseList_TalkMsgBase::umsgid() const {
  return umsgid_;
}
inline void TalkMsgBaseList_TalkMsgBase::set_umsgid(::google::protobuf::uint32 value) {
  set_has_umsgid();
  umsgid_ = value;
}

// -------------------------------------------------------------------

// TalkMsgBaseList

// repeated .tms.TalkMsgBaseList.TalkMsgBase TalkMsgBases = 1;
inline int TalkMsgBaseList::talkmsgbases_size() const {
  return talkmsgbases_.size();
}
inline void TalkMsgBaseList::clear_talkmsgbases() {
  talkmsgbases_.Clear();
}
inline const ::tms::TalkMsgBaseList_TalkMsgBase& TalkMsgBaseList::talkmsgbases(int index) const {
  return talkmsgbases_.Get(index);
}
inline ::tms::TalkMsgBaseList_TalkMsgBase* TalkMsgBaseList::mutable_talkmsgbases(int index) {
  return talkmsgbases_.Mutable(index);
}
inline ::tms::TalkMsgBaseList_TalkMsgBase* TalkMsgBaseList::add_talkmsgbases() {
  return talkmsgbases_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tms::TalkMsgBaseList_TalkMsgBase >&
TalkMsgBaseList::talkmsgbases() const {
  return talkmsgbases_;
}
inline ::google::protobuf::RepeatedPtrField< ::tms::TalkMsgBaseList_TalkMsgBase >*
TalkMsgBaseList::mutable_talkmsgbases() {
  return &talkmsgbases_;
}

// -------------------------------------------------------------------

// ChatMsgBaseList_ChatMsgBase

// required uint32 uChatID = 1 [default = 0];
inline bool ChatMsgBaseList_ChatMsgBase::has_uchatid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChatMsgBaseList_ChatMsgBase::set_has_uchatid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChatMsgBaseList_ChatMsgBase::clear_has_uchatid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChatMsgBaseList_ChatMsgBase::clear_uchatid() {
  uchatid_ = 0u;
  clear_has_uchatid();
}
inline ::google::protobuf::uint32 ChatMsgBaseList_ChatMsgBase::uchatid() const {
  return uchatid_;
}
inline void ChatMsgBaseList_ChatMsgBase::set_uchatid(::google::protobuf::uint32 value) {
  set_has_uchatid();
  uchatid_ = value;
}

// required uint32 uMsgID = 2 [default = 0];
inline bool ChatMsgBaseList_ChatMsgBase::has_umsgid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChatMsgBaseList_ChatMsgBase::set_has_umsgid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChatMsgBaseList_ChatMsgBase::clear_has_umsgid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChatMsgBaseList_ChatMsgBase::clear_umsgid() {
  umsgid_ = 0u;
  clear_has_umsgid();
}
inline ::google::protobuf::uint32 ChatMsgBaseList_ChatMsgBase::umsgid() const {
  return umsgid_;
}
inline void ChatMsgBaseList_ChatMsgBase::set_umsgid(::google::protobuf::uint32 value) {
  set_has_umsgid();
  umsgid_ = value;
}

// -------------------------------------------------------------------

// ChatMsgBaseList

// repeated .tms.ChatMsgBaseList.ChatMsgBase ChatMsgBases = 1;
inline int ChatMsgBaseList::chatmsgbases_size() const {
  return chatmsgbases_.size();
}
inline void ChatMsgBaseList::clear_chatmsgbases() {
  chatmsgbases_.Clear();
}
inline const ::tms::ChatMsgBaseList_ChatMsgBase& ChatMsgBaseList::chatmsgbases(int index) const {
  return chatmsgbases_.Get(index);
}
inline ::tms::ChatMsgBaseList_ChatMsgBase* ChatMsgBaseList::mutable_chatmsgbases(int index) {
  return chatmsgbases_.Mutable(index);
}
inline ::tms::ChatMsgBaseList_ChatMsgBase* ChatMsgBaseList::add_chatmsgbases() {
  return chatmsgbases_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tms::ChatMsgBaseList_ChatMsgBase >&
ChatMsgBaseList::chatmsgbases() const {
  return chatmsgbases_;
}
inline ::google::protobuf::RepeatedPtrField< ::tms::ChatMsgBaseList_ChatMsgBase >*
ChatMsgBaseList::mutable_chatmsgbases() {
  return &chatmsgbases_;
}

// -------------------------------------------------------------------

// UserMsgIDList_UserMsgID

// required uint32 uSendID = 1 [default = 0];
inline bool UserMsgIDList_UserMsgID::has_usendid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserMsgIDList_UserMsgID::set_has_usendid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserMsgIDList_UserMsgID::clear_has_usendid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserMsgIDList_UserMsgID::clear_usendid() {
  usendid_ = 0u;
  clear_has_usendid();
}
inline ::google::protobuf::uint32 UserMsgIDList_UserMsgID::usendid() const {
  return usendid_;
}
inline void UserMsgIDList_UserMsgID::set_usendid(::google::protobuf::uint32 value) {
  set_has_usendid();
  usendid_ = value;
}

// required uint32 uTargetID = 2 [default = 0];
inline bool UserMsgIDList_UserMsgID::has_utargetid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserMsgIDList_UserMsgID::set_has_utargetid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserMsgIDList_UserMsgID::clear_has_utargetid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserMsgIDList_UserMsgID::clear_utargetid() {
  utargetid_ = 0u;
  clear_has_utargetid();
}
inline ::google::protobuf::uint32 UserMsgIDList_UserMsgID::utargetid() const {
  return utargetid_;
}
inline void UserMsgIDList_UserMsgID::set_utargetid(::google::protobuf::uint32 value) {
  set_has_utargetid();
  utargetid_ = value;
}

// required uint32 uMsgID = 3 [default = 0];
inline bool UserMsgIDList_UserMsgID::has_umsgid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserMsgIDList_UserMsgID::set_has_umsgid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserMsgIDList_UserMsgID::clear_has_umsgid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserMsgIDList_UserMsgID::clear_umsgid() {
  umsgid_ = 0u;
  clear_has_umsgid();
}
inline ::google::protobuf::uint32 UserMsgIDList_UserMsgID::umsgid() const {
  return umsgid_;
}
inline void UserMsgIDList_UserMsgID::set_umsgid(::google::protobuf::uint32 value) {
  set_has_umsgid();
  umsgid_ = value;
}

// -------------------------------------------------------------------

// UserMsgIDList

// repeated .tms.UserMsgIDList.UserMsgID UserMsgIDs = 1;
inline int UserMsgIDList::usermsgids_size() const {
  return usermsgids_.size();
}
inline void UserMsgIDList::clear_usermsgids() {
  usermsgids_.Clear();
}
inline const ::tms::UserMsgIDList_UserMsgID& UserMsgIDList::usermsgids(int index) const {
  return usermsgids_.Get(index);
}
inline ::tms::UserMsgIDList_UserMsgID* UserMsgIDList::mutable_usermsgids(int index) {
  return usermsgids_.Mutable(index);
}
inline ::tms::UserMsgIDList_UserMsgID* UserMsgIDList::add_usermsgids() {
  return usermsgids_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tms::UserMsgIDList_UserMsgID >&
UserMsgIDList::usermsgids() const {
  return usermsgids_;
}
inline ::google::protobuf::RepeatedPtrField< ::tms::UserMsgIDList_UserMsgID >*
UserMsgIDList::mutable_usermsgids() {
  return &usermsgids_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace tms

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tms::StateServerReq_cmd>() {
  return ::tms::StateServerReq_cmd_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tms_2eproto__INCLUDED
