; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26129.0 

	TITLE	D:\Projects\fragments-of-time\windows_programming\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
EXTRN	?UsingFileMapping@@YAXXZ:PROC			; UsingFileMapping
; Function compile flags: /Odtp
; File d:\projects\fragments-of-time\windows_programming\main.cpp
_TEXT	SEGMENT
_main	PROC

; 19   : {

	push	ebp
	mov	ebp, esp

; 20   : 	UsingFileMapping();

	call	?UsingFileMapping@@YAXXZ		; UsingFileMapping

; 21   : 	
; 22   : 	return 0;

	xor	eax, eax

; 23   : }

	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
